version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: desafio_picpay_simplificado
      MYSQL_USER: venancio
      MYSQL_PASSWORD: senha_qualquer
      MYSQL_ROOT_PASSWORD: senha_qualquer_root
    ports:
      - "1224:3306"
    networks:
      - desafio_picpay_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      retries: 5

  mysql-test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: desafio_picpay_simplificado_test
      MYSQL_USER: venancio_test
      MYSQL_PASSWORD: senha_qualquer_test
      MYSQL_ROOT_PASSWORD: senha_qualquer_root_test
    ports:
      - "1225:3306"
    networks:
      - desafio_picpay_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      retries: 5

  app:
    build: .
    ports:
      - "9123:8080"
    depends_on:
      mysql:
        condition: service_healthy
      mysql-test:
        condition: service_healthy
    networks:
      - desafio_picpay_network

networks:
  desafio_picpay_network:
    driver: bridge
