spring:
  application:
    name: desafio_picpay_simplificado

  datasource:
    url: jdbc:mysql://localhost:3306/desafio_picpay_simplificado?useTimezone=true&serverTimezone=UTC
    username: root
    password: nova_senha
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
