spring:
  application:
    name: desafio_picpay_simplificado

  datasource:
    url: jdbc:mysql://mysql:3306/desafio_picpay_simplificado
    username: venancio
    password: senha_qualquer
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
