spring:
  application:
    name: desafio_picpay_simplificado

  datasource:
    url: jdbc:mysql://mysql/desafio_picpay_simplificado # para build
#    url: jdbc:mysql://localhost:1224/desafio_picpay_simplificado #para test intellij
    username: venancio
    password: senha_qualquer
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
  servlet:
    context-path: /
